/**
 * OPTIMUS — Chief of Staff Engine
 * Phase 7: Chief of Staff Intelligence Layer
 *
 * Orchestrates existing data into executive briefings, strategic recommendations,
 * and workload balancing intelligence. No new intelligence generation here,
 * just deterministic synthesis of existing engines' outputs.
 */

import { Obligation, RiskProfile, Intervention, AgentActivity } from '@/types/database';
import { ExecutiveBriefing, StrategicRecommendation, RecommendedFocus } from '@/types';
import { getActivePatterns } from './memoryEngine';
import { interventionRepo } from '../repositories';

export async function generateChiefOfStaffBriefing(
  obligations: Obligation[],
  riskProfiles: RiskProfile[],
  interventions: Intervention[],
  events: AgentActivity[], // or calendar events if passed differently
  userName: string = 'Operator'
): Promise<ExecutiveBriefing> {
  // 1. Data Aggregation & Sorting
  const activeObligations = obligations.filter(o => o.status === 'pending');
  
  // Sort risks highest to lowest
  const sortedProfiles = [...riskProfiles].sort((a, b) => b.risk_score - a.risk_score);
  const highestRiskProfile = sortedProfiles[0];
  const highestRiskObligation = highestRiskProfile 
    ? activeObligations.find(o => o.id === highestRiskProfile.obligation_id)
    : null;

  // 2. Overloaded Day Detection
  const overloadedDays = await detectOverloadedDays(activeObligations, sortedProfiles, interventions);

  // 3. Recommended Focus
  const recommendedFocus = generateRecommendedFocus(highestRiskProfile, highestRiskObligation);

  // 4. Strategic Recommendations
  const strategicRecommendations = await generateStrategicRecommendations(
    activeObligations, 
    sortedProfiles, 
    interventions,
    overloadedDays
  );

  // 5. Morning Briefing Synthesis
  const morningBriefing = generateMorningBriefing(
    activeObligations.length,
    highestRiskObligation,
    highestRiskProfile,
    overloadedDays,
    strategicRecommendations,
    userName
  );

  // 6. Evening Briefing Synthesis
  const eveningBriefing = generateEveningBriefing(obligations, sortedProfiles);

  // 7. Executive Summary
  const executiveSummary = `You have ${activeObligations.length} active commitments. ` +
    (highestRiskObligation ? `Immediate attention required on ${highestRiskObligation.title}. ` : 'All systems stable. ') +
    (overloadedDays.length > 0 ? `Warning: ${overloadedDays.join(', ')} ${overloadedDays.length > 1 ? 'are' : 'is'} overloaded.` : '');

  return {
    executiveSummary,
    morningBriefing,
    eveningBriefing,
    highestRiskTarget: highestRiskObligation?.title ?? 'None',
    recommendedFocus,
    strategicRecommendations,
    overloadedDays,
  };
}

// ─── Helpers ──────────────────────────────────────────────────

async function detectOverloadedDays(
  obligations: Obligation[],
  riskProfiles: RiskProfile[],
  interventions: Intervention[]
): Promise<string[]> {
  // Group by date
  const dayCounts: Record<string, { total: number; highRisk: number; conflicts: number }> = {};

  // Count obligations per day
  obligations.forEach(ob => {
    if (!ob.due_date) return;
    const dateStr = new Date(ob.due_date).toLocaleDateString('en-US', { weekday: 'long' });
    if (!dayCounts[dateStr]) dayCounts[dateStr] = { total: 0, highRisk: 0, conflicts: 0 };
    dayCounts[dateStr].total++;
    
    // Check if high risk
    const profile = riskProfiles.find(p => p.obligation_id === ob.id);
    if (profile && profile.risk_score >= 70) {
      dayCounts[dateStr].highRisk++;
    }
  });

  // Count conflicts (from interventions generated by calendar agent)
  interventions.forEach(inv => {
    if (inv.type.includes('Conflict') || inv.type.includes('Cluster') || inv.type.includes('Overload')) {
      // Simplistic mapping: if we had the date in the intervention, we'd map it. 
      // For now, if there are multiple conflicts overall, we might just flag 'Today' or parse the message.
      // E.g., "Multiple major commitments on 2026-06-28"
      const match = inv.message.match(/on (\d{4}-\d{2}-\d{2})/);
      if (match) {
        const dateStr = new Date(match[1]).toLocaleDateString('en-US', { weekday: 'long' });
        if (!dayCounts[dateStr]) dayCounts[dateStr] = { total: 0, highRisk: 0, conflicts: 0 };
        dayCounts[dateStr].conflicts++;
      }
    }
  });

  const overloaded: string[] = [];
  for (const [day, stats] of Object.entries(dayCounts)) {
    if (stats.highRisk > 3 || stats.total > 6 || stats.conflicts > 1) {
      overloaded.push(day);

      const interventionMsg = `${day} is overloaded. Move lower priority work to another day.`;
      const existing = interventions.find(i => i.message === interventionMsg);
      
      if (!existing && obligations.length > 0) {
        await interventionRepo.create({
          user_id: obligations[0].user_id,
          obligation_id: obligations[0].id, // Associate with the first found obligation for the day (arbitrary for a day-level alert)
          type: 'Overload',
          severity: 'High',
          message: interventionMsg,
          status: 'pending'
        });
      }
    }
  }

  return overloaded;
}

function generateRecommendedFocus(
  highestRiskProfile: RiskProfile | undefined,
  highestRiskObligation: Obligation | null | undefined
): RecommendedFocus | null {
  if (!highestRiskProfile || !highestRiskObligation) return null;

  // Extract a single sentence from reasoning or future outcomes
  let reason = highestRiskProfile.reasoning || `Highest risk (${Math.round(highestRiskProfile.risk_score)}) with impending deadline.`;
  
  if (highestRiskProfile.future_outcomes?.outcomes?.length > 0) {
    const dangerOutcome = highestRiskProfile.future_outcomes.outcomes.find((o: any) => o.type === 'Danger');
    if (dangerOutcome) {
      reason += ` Warning: ${dangerOutcome.summary}`;
    }
  }

  // Calculate confidence inversely based on risk (just a deterministic proxy for confidence in the plan)
  const confidence = Math.max(0, 100 - (highestRiskProfile.risk_score * 0.5));

  return {
    title: highestRiskObligation.title,
    reason,
    confidence: Math.round(confidence),
  };
}

async function generateStrategicRecommendations(
  obligations: Obligation[],
  riskProfiles: RiskProfile[],
  interventions: Intervention[],
  overloadedDays: string[]
): Promise<StrategicRecommendation[]> {
  const recommendations: StrategicRecommendation[] = [];
  const memoryPatterns = await getActivePatterns();

  // 1. Address Highest Risk
  if (riskProfiles.length > 0) {
    const highest = riskProfiles[0];
    const ob = obligations.find(o => o.id === highest.obligation_id);
    if (ob) {
      let recStr = `Finish ${ob.title} before beginning other work.`;
      
      // If we have a second highest, add context
      if (riskProfiles.length > 1) {
        const second = obligations.find(o => o.id === riskProfiles[1].obligation_id);
        if (second) {
          recStr = `Finish ${ob.title} before continuing ${second.title} work.`;
        }
      }

      recommendations.push({
        priority: 1,
        recommendation: recStr,
        reason: `Risk score is ${Math.round(highest.risk_score)}, deadline proximity is critical${overloadedDays.length > 0 ? `, and ${overloadedDays[0]} contains conflicts` : ''}.`,
        confidence: 0.85,
      });
    }
  }

  // 2. Address Overloaded Days
  if (overloadedDays.length > 0) {
    recommendations.push({
      priority: 2,
      recommendation: `Reschedule lower-priority tasks away from ${overloadedDays.join(' and ')}.`,
      reason: `Workload exceeds safe limits (>6 total or >3 high risk obligations) on these days.`,
      confidence: 0.90,
    });
  }

  // 3. Interventions based
  const criticalIntervention = interventions.find(i => i.severity.toLowerCase() === 'critical');
  if (criticalIntervention && criticalIntervention.obligation_id) {
    const ob = obligations.find(o => o.id === criticalIntervention.obligation_id);
    if (ob && !recommendations.some(r => r.recommendation.includes(ob.title))) {
       recommendations.push({
        priority: 3,
        recommendation: `Address critical alert for ${ob.title} immediately.`,
        reason: criticalIntervention.message,
        confidence: 0.95,
      });
    }
  }

  // 4. Memory Pattern based
  if (memoryPatterns.length > 0) {
    const topPattern = memoryPatterns.sort((a, b) => b.occurrences - a.occurrences)[0];
    recommendations.push({
      priority: 4,
      recommendation: topPattern.recommendation,
      reason: `Based on historical pattern: ${topPattern.pattern} (observed ${topPattern.occurrences} times).`,
      confidence: 0.75,
    });
  }

  // Ensure priority numbering is sequential
  return recommendations.map((r, i) => ({ ...r, priority: i + 1 })).slice(0, 3);
}

function generateMorningBriefing(
  activeCount: number,
  highestRiskObligation: Obligation | null | undefined,
  highestRiskProfile: RiskProfile | undefined,
  overloadedDays: string[],
  recommendations: StrategicRecommendation[],
  userName: string
): string {
  let briefing = `Good morning, ${userName || 'Operator'}.\n\n`;
  briefing += `You have ${activeCount} active commitments.\n\n`;

  if (highestRiskObligation && highestRiskProfile) {
    briefing += `The highest-risk target is:\n${highestRiskObligation.title} (${Math.round(highestRiskProfile.risk_score)}%).\n\n`;
  }

  if (overloadedDays.length > 0) {
    briefing += `${overloadedDays[0]} contains overlapping or excessive obligations.\n\n`;
  }

  if (recommendations.length > 0) {
    briefing += `Recommended focus:\n`;
    recommendations.forEach((r, idx) => {
      briefing += `${idx + 1}. ${r.recommendation}\n`;
    });
    briefing += '\n';
  }

  // Calculate an arbitrary but deterministic confidence score based on avg risk
  const conf = highestRiskProfile ? Math.max(40, 100 - highestRiskProfile.risk_score) : 95;
  briefing += `Overall confidence:\n${Math.round(conf)}%.`;

  return briefing;
}

function generateEveningBriefing(
  allObligations: Obligation[],
  riskProfiles: RiskProfile[]
): string {
  // Simplistic determination of "completed today"
  const todayDateStr = new Date().toISOString().split('T')[0];
  const completedToday = allObligations.filter(o => 
    o.status === 'completed' && 
    o.updated_at.startsWith(todayDateStr)
  ).length;

  const activeProfiles = riskProfiles.filter(p => {
    const ob = allObligations.find(o => o.id === p.obligation_id);
    return ob && ob.status === 'pending';
  });

  const criticalCount = activeProfiles.filter(p => p.risk_band.toLowerCase().includes('critical')).length;
  const monitorCount = activeProfiles.filter(p => p.risk_band.toLowerCase().includes('monitor')).length;

  // Simple deterministic risk reduction proxy
  const riskReduction = completedToday > 0 ? (completedToday * 4) + 2 : 0; 

  let briefing = `Today you completed ${completedToday} commitments.\n\n`;
  
  if (riskReduction > 0) {
    briefing += `Risk exposure reduced by ${riskReduction}%.\n\n`;
  }

  briefing += `Tomorrow contains:\n`;
  briefing += `- ${criticalCount} Critical obligation${criticalCount !== 1 ? 's' : ''}\n`;
  briefing += `- ${monitorCount} Monitor obligation${monitorCount !== 1 ? 's' : ''}\n\n`;

  const recommendedStart = criticalCount > 0 ? '8:30 AM' : '9:30 AM';
  briefing += `Recommended start time:\n${recommendedStart}.`;

  return briefing;
}
